import type { CreateQuestionInput } from "@/types/sleepAssessment.types";

export const defaultSleepAssessmentQuestions: CreateQuestionInput[] = [
  {
    questionKey: "sleep_difficulty",
    questionText: "Do you have difficulty falling asleep?",
    questionType: "single_choice",
    order: 1,
    isRequired: true,
    isActive: true,
    category: "sleep_patterns",
    options: [
      { id: "1", label: "Rarely or never", value: "rarely" },
      { id: "2", label: "Sometimes", value: "sometimes" },
      { id: "3", label: "Often", value: "often" },
      { id: "4", label: "Almost every night", value: "always" },
    ],
  },
  {
    questionKey: "sleep_hours",
    questionText: "How many hours of sleep do you get on average per night?",
    questionType: "single_choice",
    order: 2,
    isRequired: true,
    isActive: true,
    category: "sleep_patterns",
    options: [
      { id: "1", label: "Less than 4 hours", value: "less_4" },
      { id: "2", label: "4-5 hours", value: "4_5" },
      { id: "3", label: "5-6 hours", value: "5_6" },
      { id: "4", label: "6-7 hours", value: "6_7" },
      { id: "5", label: "7-8 hours", value: "7_8" },
      { id: "6", label: "More than 8 hours", value: "more_8" },
    ],
  },
  {
    questionKey: "wake_up_frequency",
    questionText: "How often do you wake up during the night?",
    questionType: "single_choice",
    order: 3,
    isRequired: true,
    isActive: true,
    category: "sleep_patterns",
    options: [
      { id: "1", label: "Never or rarely", value: "never" },
      { id: "2", label: "Once a night", value: "once" },
      { id: "3", label: "2-3 times a night", value: "2_3_times" },
      { id: "4", label: "More than 3 times", value: "more_3" },
    ],
  },
  {
    questionKey: "sleep_quality",
    questionText: "How would you rate your overall sleep quality?",
    questionType: "scale",
    order: 4,
    isRequired: true,
    isActive: true,
    category: "sleep_quality",
    options: [
      { id: "1", label: "1", value: "1" },
      { id: "2", label: "2", value: "2" },
      { id: "3", label: "3", value: "3" },
      { id: "4", label: "4", value: "4" },
      { id: "5", label: "5", value: "5" },
      { id: "6", label: "6", value: "6" },
      { id: "7", label: "7", value: "7" },
      { id: "8", label: "8", value: "8" },
      { id: "9", label: "9", value: "9" },
      { id: "10", label: "10", value: "10" },
    ],
  },
  {
    questionKey: "morning_feeling",
    questionText: "How do you usually feel when you wake up in the morning?",
    questionType: "single_choice",
    order: 5,
    isRequired: true,
    isActive: true,
    category: "sleep_quality",
    options: [
      { id: "1", label: "Refreshed and energized", value: "refreshed" },
      { id: "2", label: "Somewhat rested", value: "somewhat_rested" },
      { id: "3", label: "Still tired", value: "tired" },
      { id: "4", label: "Exhausted", value: "exhausted" },
    ],
  },
  {
    questionKey: "caffeine_consumption",
    questionText: "How much caffeine do you consume daily?",
    questionType: "single_choice",
    order: 6,
    isRequired: true,
    isActive: true,
    category: "lifestyle",
    options: [
      { id: "1", label: "None", value: "none" },
      { id: "2", label: "1-2 cups of coffee/tea", value: "1_2_cups" },
      { id: "3", label: "3-4 cups of coffee/tea", value: "3_4_cups" },
      { id: "4", label: "More than 4 cups", value: "more_4" },
    ],
  },
  {
    questionKey: "screen_time_before_bed",
    questionText:
      "Do you use electronic devices (phone, TV, computer) before bed?",
    questionType: "single_choice",
    order: 7,
    isRequired: true,
    isActive: true,
    category: "lifestyle",
    options: [
      { id: "1", label: "Never", value: "never" },
      { id: "2", label: "Sometimes (1-2 times a week)", value: "sometimes" },
      { id: "3", label: "Often (3-5 times a week)", value: "often" },
      { id: "4", label: "Every night", value: "every_night" },
    ],
  },
  {
    questionKey: "stress_level",
    questionText: "How would you describe your current stress level?",
    questionType: "single_choice",
    order: 8,
    isRequired: true,
    isActive: true,
    category: "wellbeing",
    options: [
      { id: "1", label: "Low - I feel relaxed most of the time", value: "low" },
      { id: "2", label: "Moderate - Occasional stress", value: "moderate" },
      { id: "3", label: "High - Often stressed", value: "high" },
      { id: "4", label: "Very high - Constantly stressed", value: "very_high" },
    ],
  },
  {
    questionKey: "exercise_frequency",
    questionText: "How often do you exercise?",
    questionType: "single_choice",
    order: 9,
    isRequired: true,
    isActive: true,
    category: "lifestyle",
    options: [
      { id: "1", label: "Never", value: "never" },
      { id: "2", label: "1-2 times a week", value: "1_2_week" },
      { id: "3", label: "3-4 times a week", value: "3_4_week" },
      { id: "4", label: "Daily", value: "daily" },
    ],
  },
  {
    questionKey: "sleep_environment",
    questionText: "How would you describe your sleep environment?",
    questionType: "multiple_choice",
    order: 10,
    isRequired: true,
    isActive: true,
    category: "environment",
    options: [
      { id: "1", label: "Dark room", value: "dark" },
      { id: "2", label: "Quiet environment", value: "quiet" },
      { id: "3", label: "Comfortable temperature", value: "comfortable_temp" },
      {
        id: "4",
        label: "Comfortable mattress/pillow",
        value: "comfortable_bed",
      },
      {
        id: "5",
        label: "Room has distractions (TV, work desk)",
        value: "distractions",
      },
    ],
  },
  {
    questionKey: "sleep_schedule",
    questionText: "Do you maintain a consistent sleep schedule?",
    questionType: "single_choice",
    order: 11,
    isRequired: true,
    isActive: true,
    category: "sleep_patterns",
    options: [
      { id: "1", label: "Yes, same time every day", value: "consistent" },
      { id: "2", label: "Mostly consistent on weekdays", value: "weekdays" },
      { id: "3", label: "Varies significantly", value: "varies" },
      { id: "4", label: "No regular schedule", value: "no_schedule" },
    ],
  },
  {
    questionKey: "daytime_sleepiness",
    questionText: "Do you experience excessive daytime sleepiness?",
    questionType: "single_choice",
    order: 12,
    isRequired: true,
    isActive: true,
    category: "sleep_quality",
    options: [
      { id: "1", label: "Rarely or never", value: "rarely" },
      { id: "2", label: "Sometimes", value: "sometimes" },
      { id: "3", label: "Often", value: "often" },
      { id: "4", label: "Almost every day", value: "daily" },
    ],
  },
  {
    questionKey: "sleep_issues",
    questionText: "Do you experience any of the following sleep issues?",
    questionType: "multiple_choice",
    order: 13,
    isRequired: false,
    isActive: true,
    category: "health",
    options: [
      { id: "1", label: "Snoring", value: "snoring" },
      { id: "2", label: "Sleep apnea", value: "sleep_apnea" },
      { id: "3", label: "Restless legs", value: "restless_legs" },
      { id: "4", label: "Nightmares", value: "nightmares" },
      { id: "5", label: "Sleepwalking", value: "sleepwalking" },
      { id: "6", label: "None of the above", value: "none" },
    ],
  },
  {
    questionKey: "sleep_goals",
    questionText: "What are your main sleep goals?",
    questionType: "multiple_choice",
    order: 14,
    isRequired: true,
    isActive: true,
    category: "goals",
    options: [
      { id: "1", label: "Fall asleep faster", value: "fall_asleep_faster" },
      { id: "2", label: "Sleep through the night", value: "sleep_through" },
      { id: "3", label: "Wake up feeling refreshed", value: "wake_refreshed" },
      { id: "4", label: "Establish a consistent routine", value: "routine" },
      {
        id: "5",
        label: "Reduce anxiety around sleep",
        value: "reduce_anxiety",
      },
    ],
  },
  {
    questionKey: "additional_info",
    questionText:
      "Is there anything else you would like us to know about your sleep?",
    questionType: "text",
    order: 15,
    isRequired: false,
    isActive: true,
    category: "general",
    options: [],
  },
];
